services:
  ros2_lab:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mobile_robot_container
    volumes:
      - ./src:/workspace/src
      - ./data:/workspace/data
      - ./report:/workspace/report
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - DISPLAY=host.docker.internal:0
